//-------------------------------------------------------------------------------------------------
//-------------------------------------------------------------------------------------------------
Ray f_cameraNormRay(vec2 uv) {
	vec3 dir = normalize(KL_camera.p_uv + (KL_camera.p_u * uv.x) + (KL_camera.p_v * uv.y) - KL_camera.position);
	return Ray(KL_camera.position, dir, 1.0 / dir);
}

//-------------------------------------------------------------------------------------------------
//-------------------------------------------------------------------------------------------------
Ray f_cameraRay(vec2 uv) {
	float pixel_size = 1.0 / KL_resolution.x;

	vec3 ray_dir = normalize(KL_camera.p_uv + (KL_camera.p_u * uv.x) + (KL_camera.p_v * uv.y) - KL_camera.position);
	vec3 focal_point = KL_camera.position + ray_dir * KL_camera.focal_distance;

	vec2 aperture_offset = f_randUnitDisk() * pixel_size * KL_camera.aperture * 0.5;
	vec3 lens_offset = KL_camera.position + KL_camera.x_vec * aperture_offset.x + KL_camera.y_vec * aperture_offset.y;
	vec3 new_direction = normalize(focal_point - lens_offset);

	return Ray(KL_camera.position, new_direction, 1.0 / new_direction);
}

//-------------------------------------------------------------------------------------------------
//-------------------------------------------------------------------------------------------------
Ray f_cameraOrthoRay(vec2 uv) {
	float ortho_scale = 0.05;
	return Ray(KL_camera.position + (KL_camera.p_u * uv.x * ortho_scale) + (KL_camera.p_v * uv.y* ortho_scale), normalize(KL_camera.z_vec), 1.0 / normalize(KL_camera.z_vec));
}