//-------------------------------------------------------------------------------------------------
//-------------------------------------------------------------------------------------------------
Ray f_cameraNormRay(vec2 uv) {
	return Ray(camera.position, normalize(camera.p_uv + (camera.p_u * uv.x) + (camera.p_v * uv.y) - camera.position));
}

//-------------------------------------------------------------------------------------------------
//-------------------------------------------------------------------------------------------------
Ray f_cameraRay(vec2 uv) {
	float pixel_size = 1.0 / resolution.x;

	vec3 ray_dir = normalize(camera.p_uv + (camera.p_u * uv.x) + (camera.p_v * uv.y) - camera.position);
	vec3 focal_point = camera.position + ray_dir * camera.focal_distance;

	vec2 aperture_offset = f_randUnitDisk() * pixel_size * camera.aperture * 0.5;
	vec3 lens_offset = camera.position + camera.x_vec * aperture_offset.x + camera.y_vec * aperture_offset.y;
	vec3 new_direction = normalize(focal_point - lens_offset);

	return Ray(camera.position, new_direction);
}

//-------------------------------------------------------------------------------------------------
//-------------------------------------------------------------------------------------------------
Ray f_cameraOrthoRay(vec2 uv) {
	float ortho_scale = 0.03;
	return Ray(camera.position + (camera.p_u * uv.x * ortho_scale) + (camera.p_v * uv.y* ortho_scale), normalize(camera.z_vec));
}