//-------------------------------------------------------------------------------------------------
//-------------------------------------------------------------------------------------------------
#version 460

#include "Globals.comp"
#include "Inputs.comp"
#include "Utilities.comp"
#include "Random.comp"
#include "Intersections.comp"
#include "Hook.comp"
#include "Camera.comp"
#include "Pathtrace.comp"
#include "Debug.comp"
#include "Render.comp"

//-------------------------------------------------------------------------------------------------
//-------------------------------------------------------------------------------------------------
void main() {
	ivec2 pixel_id = ivec2(gl_GlobalInvocationID.xy);
	vec2 uv = (pixel_id - 1 - vec2(resolution) / 2.0) / float(max(resolution.x, resolution.y));
	f_initRNG(pixel_id, frame_count);

	vec4 pixel_color = f_render(uv, pixel_id);
	imageStore(raw_render_layer, pixel_id, pixel_color);
}