//-------------------------------------------------------------------------------------------------
//-------------------------------------------------------------------------------------------------
#version 460

#include "Globals.comp"
#include "Inputs.comp"
#include "Bits.comp"
#include "Utilities.comp"
#include "Random.comp"
#include "Intersections.comp"
#include "Hook.comp"
#include "Camera.comp"
#include "Pathtrace.comp"
#include "Debug.comp"
#include "Render.comp"

//-------------------------------------------------------------------------------------------------
//-------------------------------------------------------------------------------------------------
void main() {
	ivec2 pixel_id = ivec2(gl_GlobalInvocationID.xy);
	vec2 uv = (pixel_id - 1 - vec2(KL_resolution) / 2.0) / float(max(KL_resolution.x, KL_resolution.y));
	f_initRNG(pixel_id, KL_frame_count);

	vec4 pixel_color = f_render(uv, pixel_id);
	//vec4 pixel_color = KL_BUFFER_mesh_instances.length() > 0 ? vec4(1) : vec4(1,0,1,1);
	imageStore(KL_raw_render_layer, pixel_id, pixel_color);
}