//-------------------------------------------------------------------------------------------------
//-------------------------------------------------------------------------------------------------
void f_debugRender(in vec2 uv, in ivec2 pixel_id) {
	Ray ray = f_cameraNormRay(uv);
	Hit hit_data = f_hit();
	f_sceneIntersection(ray, hit_data);

	float bvh_alpha = 1.0;
	for (int i = 0; i < hit_data.bvh_depth; i++) {
		bvh_alpha *= 0.95;
	}
	imageStore(KL_bvh_render_layer, pixel_id, vec4(vec3(1-bvh_alpha), 1));
	imageStore(KL_normal_render_layer, pixel_id, vec4(abs(hit_data.hit_normal), 1));
}