//-------------------------------------------------------------------------------------------------
//-------------------------------------------------------------------------------------------------
vec4 f_hook(inout Hit hit_data, inout State state, inout Ray ray) {

	if (hit_data.material == MAX_UINT) {
		ray.direction = reflect(ray.direction, hit_data.hit_normal);
		ray.origin = hit_data.hit_pos + ray.direction * EPSILON;
		return vec4(0.2, 0.0, 0.2, 1.0);
	}//---INSERT-SHADERS---//


	// ERROR
	hit_data.error = true;
	return vec4(1, 0, 1, 1);
}