//-------------------------------------------------------------------------------------------------
//-------------------------------------------------------------------------------------------------
vec4 f_pathTrace(in Ray ray, in ivec2 pixel_id) {
	vec3 radiance = vec3(0.0);
	vec3 throughput = vec3(1.0);
	State state;
	LightSampleRec lightSample;
	BsdfSampleRec bsdfSample;

	vec4 render_output = vec4(0);

	Hit hit_data = f_hit();
	f_sceneIntersection(ray, hit_data);

	render_output = f_hook(hit_data, state, ray);

	return render_output;
}