//-------------------------------------------------------------------------------------------------
//-------------------------------------------------------------------------------------------------
void f_accumulate(in vec4 color, in ivec2 pixel_id) {
	vec4 previous_color = imageLoad(accumulation_render_layer, pixel_id);
	if (current_sample == 0) {
		previous_color = vec4(0);
	}

	float weight = float(current_sample);
	vec4 full_color = (previous_color * weight + color) / (weight + 1.0);
	imageStore(accumulation_render_layer, pixel_id, vec4(full_color.rgb / full_color.a, 1.0));
}
//-------------------------------------------------------------------------------------------------
//-------------------------------------------------------------------------------------------------
vec4 f_render(in vec2 uv, in ivec2 pixel_id) {
	f_debugRender(uv, pixel_id);

	Ray ray = f_cameraRay(uv);
	vec4 pixel_color = f_pathTrace(ray, pixel_id);
	f_accumulate(pixel_color, pixel_id);

	return pixel_color;
}