//-------------------------------------------------------------------------------------------------
//-------------------------------------------------------------------------------------------------
#version 460
#include "Globals.comp"
#include "Inputs.comp"
#include "Utilities.comp"
#include "Random.comp"
#include "Intersections.comp"
#include "Hook.comp"
#include "Pathtrace.comp"
//-------------------------------------------------------------------------------------------------
//-------------------------------------------------------------------------------------------------
void main() {
	ivec2 pixel_id = ivec2(gl_GlobalInvocationID.xy);
	vec2 uv = (pixel_id - 1 - vec2(resolution) / 2.0) / float(max(resolution.x, resolution.y));

	vec4 color = f_render(uv, pixel_id);

	vec4 previous_color = imageLoad(accumulation_render_layer, pixel_id);
	if (frame_count == 0 || bool(reset)) previous_color = vec4(0);

	vec4 full_color = previous_color + color;
	imageStore(accumulation_render_layer, pixel_id, vec4(full_color.rgb / full_color.a, 1));
	imageStore(raw_render_layer, pixel_id, color);
}